version: '3'

services:
  docker-mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=contact
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3307:3306

  app:
    image: demo:latest
    ports:
      - 8083:8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-standalone:3306/contact
    depends_on:
      - docker-mysql